services:
  subscriber:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.subscriber-template.entrypoints: "web"
      traefik.http.routers.subscriber-template.rule: "Host(`subscriber-template.localtest.me`)"
      traefik.http.services.subscriber-template.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: subscriber-template
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: subscriber-template.localtest.me
    networks:
      - default
      - proxy

  publisher1:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.publisher1.entrypoints: "web"
      traefik.http.routers.publisher1.rule: "Host(`publisher1.localtest.me`)"
      traefik.http.services.publisher1.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: publisher1
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: publisher1.localtest.me
    networks:
      - default
      - proxy

  publisher2:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.publisher2.entrypoints: "web"
      traefik.http.routers.publisher2.rule: "Host(`publisher2.localtest.me`)"
      traefik.http.services.publisher2.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: publisher2
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: publisher2.localtest.me
    networks:
      - default
      - proxy

  publisher3:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.publisher3.entrypoints: "web"
      traefik.http.routers.publisher3.rule: "Host(`publisher3.localtest.me`)"
      traefik.http.services.publisher3.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: publisher3
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: publisher3.localtest.me
    networks:
      - default
      - proxy

  broker:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.broker-template.entrypoints: "web"
      traefik.http.routers.broker-template.rule: "Host(`broker-template.localtest.me`)"
      traefik.http.services.broker-template.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: broker-template
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy